/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as SessionRouteImport } from './routes/session'
import { Route as ClinicianIndexRouteImport } from './routes/clinician.index'
import { Route as ClinicianPatientIdRouteImport } from './routes/clinician.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicianIndexRoute = ClinicianIndexRouteImport.update({
  id: '/clinician/',
  path: '/clinician/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicianPatientIdRoute = ClinicianPatientIdRouteImport.update({
  id: '/clinician/$patientId',
  path: '/clinician/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/session': typeof SessionRoute
  '/clinician/$patientId': typeof ClinicianPatientIdRoute
  '/clinician/': typeof ClinicianIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/session': typeof SessionRoute
  '/clinician/$patientId': typeof ClinicianPatientIdRoute
  '/clinician': typeof ClinicianIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/session': typeof SessionRoute
  '/clinician/$patientId': typeof ClinicianPatientIdRoute
  '/clinician/': typeof ClinicianIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/consent' | '/session' | '/clinician/$patientId' | '/clinician/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/consent' | '/session' | '/clinician/$patientId' | '/clinician'
  id:
    | '__root__'
    | '/'
    | '/consent'
    | '/session'
    | '/clinician/$patientId'
    | '/clinician/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsentRoute: typeof ConsentRoute
  SessionRoute: typeof SessionRoute
  ClinicianPatientIdRoute: typeof ClinicianPatientIdRoute
  ClinicianIndexRoute: typeof ClinicianIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinician/': {
      id: '/clinician/'
      path: '/clinician'
      fullPath: '/clinician/'
      preLoaderRoute: typeof ClinicianIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinician/$patientId': {
      id: '/clinician/$patientId'
      path: '/clinician/$patientId'
      fullPath: '/clinician/$patientId'
      preLoaderRoute: typeof ClinicianPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsentRoute: ConsentRoute,
  SessionRoute: SessionRoute,
  ClinicianPatientIdRoute: ClinicianPatientIdRoute,
  ClinicianIndexRoute: ClinicianIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
